
spring.application.name=Second-Project
spring.datasource.url=jdbc:mysql://localhost:3306/second_project_db
spring.datasource.username=root
spring.datasource.password=ayush7697	
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dct0bvygk}
cloudinary.api_key=${CLOUDINARY_API_KEY:724246357716861}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:5FGbuNZh247QCS4Xz1kWEn3_3tE}